### PR TITLE
Cfg

### PR DESCRIPTION
**Pull request by boyingl**

### CODE REVIEW

**Comment by wmdietl** [comment]
This looks identical to https://github.com/eisop/webserver/pull/29 . Can one of them be closed?

**Comment by CharlesZ-Chen** [comment]
#29 is created against our `master` branch, but this PR is not a mature feature that ready to be merged into `master`. So I told Ashley to create a new PR against to her own `ashley-master` branch on our repo. Will close #29 .

**Comment by CharlesZ-Chen** [comment]
As I discussed on Tuesday in person with Ashley, we will make some change in Checker-Framework to let it output the dot file as string rather than write into files. Then we will invoke CFG mode in a different way in our server. That means most of the content of this PR will be updates. At the moment, I will just leave this PR open, and wait Ashley to push more updates of our new way, then will start PR review again.

**Comment by wmdietl** [comment]
Opened #40 to implement this properly.

**Pull request closed without merging**
